//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinylRecodShop.Model.Database.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class VinylRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> ReleaseYear { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string CountryCode { get; set; }
        public short VinylType { get; set; }
        public int Cost { get; set; }
        public Nullable<int> GenreId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
